#!/usr/bin/env bash
# Tests for the release checksum step (.github/scripts/pack-checksums.sh) and for
# the workflow that used to carry that logic inline in build.yml.
#
# Why a test file for a workflow step exists at all: the manifest bug this fixed
# (SHA256SUMS.txt generated by `sha256sum ./*` *after* a sidecar was written per
# payload, so 2N lines against a count of N) was invisible to every reader because
# the shell body lives in YAML. Nobody can run a YAML heredoc on their laptop, so
# nobody did, and the publish job has been unable to pass since the sidecars were
# added. Extracting the logic is what makes it testable; this file is the test.
#
# Usage:
#   bash .github/scripts/test-pack-checksums.sh                 # the suite
#   bash .github/scripts/test-pack-checksums.sh --against-workflow FILE
#        # run the suite against the inline `Pack + checksums` body of a workflow
#        # (this is how the pre-fix build.yml was shown to fail)
#   bash .github/scripts/test-pack-checksums.sh --selftest-fail
#        # run the suite against the pre-fix logic, kept here verbatim, and prove
#        # the suite notices
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
SCRIPT="$HERE/pack-checksums.sh"
WORKFLOW="$REPO/.github/workflows/build.yml"

PASS=0
FAILED=0
ok() {
  PASS=$((PASS + 1))
  printf '  ok   %s\n' "$*"
}
no() {
  FAILED=$((FAILED + 1))
  printf '  FAIL %s\n' "$*"
}

# ── fixtures ─────────────────────────────────────────────────────────────────
# At least two payloads, three extensions, and a nested path: the flattening step
# has to survive a basename collision check, and one manifest line per payload is
# only interesting when there is more than one of each.
make_dist() {
  local d=$1
  mkdir -p "$d/dist/windows" "$d/dist/android/deep"
  printf 'installer bytes\n' >"$d/dist/windows/AetherNext-windows-x64-setup.exe"
  printf 'portable bytes\n' >"$d/dist/windows/AetherNext-portable-windows-x64.zip"
  printf 'engine bytes\n' >"$d/dist/android/deep/AetherNext-android-arm64-v8a.apk"
  # Scaffolding that must never reach the release directory.
  printf 'notes\n' >"$d/dist/windows/README.txt"
}

PAYLOAD_NAMES=(
  AetherNext-windows-x64-setup.exe
  AetherNext-portable-windows-x64.zip
  AetherNext-android-arm64-v8a.apk
)

# ── suite A: the step packs a manifest that describes exactly its payloads ───
run_pack() { # $1 impl, $2 workdir
  local impl=$1 d=$2 out
  out=$(cd "$d" && GITHUB_REF=refs/tags/v9.9.9 GITHUB_REF_NAME=v9.9.9 \
    GITHUB_OUTPUT="$d/gh-output" bash "$impl" --src dist --out out 2>&1)
  echo "$?"
  printf '%s\n' "$out" >"$d/pack.log"
}

suite_behaviour() { # $1 impl, $2 workdir
  local impl=$1 d=$2
  local -a codes=()
  local rc
  rc=$(run_pack "$impl" "$d" | head -1)
  if [ "$rc" = "0" ]; then
    ok "(a) pack step succeeds with ${#PAYLOAD_NAMES[@]} payloads"
  else
    no "(a) pack step failed (exit $rc): $(tail -3 "$d/pack.log" | tr '\n' ' ')"
    return
  fi

  local m="$d/out/SHA256SUMS.txt"
  if [ -s "$m" ]; then
    ok "SHA256SUMS.txt exists and is not empty"
  else
    no "SHA256SUMS.txt is missing or empty"
    return
  fi

  local lines
  lines=$(grep -c . "$m")
  if [ "$lines" = "${#PAYLOAD_NAMES[@]}" ]; then
    ok "(b) manifest has $lines line(s) for $lines payload(s)"
  else
    no "(b) manifest has $lines line(s) for ${#PAYLOAD_NAMES[@]} payload(s) - it hashes generated files too"
  fi

  local n hits bad=0
  for n in "${PAYLOAD_NAMES[@]}"; do
    hits=$(awk -v n="./$n" '{ g = $2; sub(/^\*/, "", g); if (g == n) c += 1 } END { print c + 0 }' "$m")
    [ "$hits" = "1" ] || {
      no "(b) $n appears $hits time(s) in the manifest, want exactly once"
      bad=1
    }
  done
  [ "$bad" = "0" ] && ok "(b) every payload appears exactly once in the manifest"

  local sidecar_lines
  sidecar_lines=$(find "$d/out" -maxdepth 1 -name '*.sha256' | wc -l)
  if [ "$sidecar_lines" = "${#PAYLOAD_NAMES[@]}" ]; then
    ok "(c) $sidecar_lines per-file sidecar(s) for ${#PAYLOAD_NAMES[@]} payload(s)"
  else
    no "(c) $sidecar_lines sidecar(s) for ${#PAYLOAD_NAMES[@]} payload(s)"
  fi

  bad=0
  for n in "${PAYLOAD_NAMES[@]}"; do
    if [ ! -f "$d/out/$n.sha256" ]; then
      no "(c) out/$n.sha256 is absent"
      bad=1
      continue
    fi
    if ! (cd "$d/out" && sha256sum -c --quiet "./$n.sha256" >/dev/null 2>&1); then
      no "(c) out/$n.sha256 does not verify against $n"
      bad=1
      continue
    fi
    local want have
    want=$(sha256sum "$d/out/$n" | awk '{print $1}')
    have=$(awk -v n="./$n" '{ g = $2; sub(/^\*/, "", g); if (g == n) print $1 }' "$m")
    [ "$want" = "$have" ] || {
      no "(c) manifest digest for $n is $have, the bytes say $want"
      bad=1
    }
  done
  [ "$bad" = "0" ] && ok "(c) every payload has a sidecar, and it matches the manifest and its bytes"

  if ! (cd "$d/out" && sha256sum -c --quiet SHA256SUMS.txt >/dev/null 2>&1); then
    no "SHA256SUMS.txt does not verify against the release directory"
  else
    ok "SHA256SUMS.txt verifies against the release directory"
  fi

  if grep -q '\.sha256' "$m"; then
    no "manifest lists .sha256 files as artifacts"
  else
    ok "manifest lists no generated file"
  fi

  if [ -e "$d/out/README.txt" ]; then
    no "non-payload scaffolding (README.txt) was flattened into the release"
  else
    ok "only .exe/.zip/.apk payloads were flattened"
  fi

  local tag
  tag=$(grep '^tag=' "$d/gh-output" 2>/dev/null | cut -d= -f2-)
  if [ "$tag" = "v9.9.9" ]; then
    ok "a tag run emits tag=v9.9.9 for the release step"
  else
    no "tag run emitted tag='$tag' (want v9.9.9); GITHUB_OUTPUT=${GITHUB_OUTPUT:-unset}"
  fi
}

# ── suite B: the verifier refuses a manifest that lies ───────────────────────
# Only meaningful for an implementation with a re-verify mode; the point is that the
# step *fails* rather than publishing, which is the property the old step lacked.
suite_refusals() { # $2 workdir already packed by $SCRIPT
  local d=$1 n
  for n in "drop a payload line" "add a stale line" "corrupt a sidecar"; do
    local work="$d/mut-$RANDOM"
    cp -r "$d/out" "$work"
    case $n in
    "drop a payload line")
      grep -v -F -- "./${PAYLOAD_NAMES[0]}" "$work/SHA256SUMS.txt" >"$work/tmp" &&
        mv "$work/tmp" "$work/SHA256SUMS.txt"
      ;;
    "add a stale line")
      printf '%s  ./not-in-this-release.exe\n' "$(printf 'x' | sha256sum | cut -d' ' -f1)" \
        >>"$work/SHA256SUMS.txt"
      ;;
    "corrupt a sidecar")
      printf 'deadbeef  ./%s\n' "${PAYLOAD_NAMES[1]}" >"$work/${PAYLOAD_NAMES[1]}.sha256"
      ;;
    esac
    if (cd "$work" && bash "$SCRIPT" --verify-only . >/dev/null 2>&1); then
      no "(d) $n: --verify-only accepted a manifest that does not describe the directory"
    else
      ok "(d) $n: --verify-only refuses"
    fi
  done

  # A payload that arrives after the manifest is written is invisible to a
  # generator-only step; it must not survive the re-check.
  local work="$d/mut-late"
  cp -r "$d/out" "$work"
  printf 'late drop\n' >"$work/evil-payload.exe"
  if (cd "$work" && bash "$SCRIPT" --verify-only . >/dev/null 2>&1); then
    no "(d) --verify-only accepted an unpacked payload with no manifest line"
  else
    ok "(d) --verify-only refuses a payload that is missing from the manifest"
  fi
}

suite_flatten_collision() {
  local d=$1
  mkdir -p "$d/collide/windows-a" "$d/collide/windows-b"
  printf 'one\n' >"$d/collide/windows-a/same-name.exe"
  printf 'two\n' >"$d/collide/windows-b/same-name.exe"
  if (cd "$d/collide" && bash "$SCRIPT" --src . --out out >/dev/null 2>&1); then
    no "two payloads with the same basename flatten silently into out/"
  else
    ok "two payloads with the same basename are refused, not overwritten"
  fi
}

# ── static: the workflow must not carry this logic any more ──────────────────
suite_workflow() {
  local wf=${1:-$WORKFLOW}
  local body code
  body=$(extract_pack_step "$wf")
  if [ -z "$body" ]; then
    no "no 'Pack + checksums' step found in $(basename "$wf")"
    return
  fi
  # Comments are prose about the old defect, not code; only the executable lines
  # may carry checksum logic.
  code=$(printf '%s\n' "$body" | grep -v '^[[:space:]]*#')
  if printf '%s\n' "$code" | grep -q 'sha256\|SHA256SUMS'; then
    no "build.yml still computes checksums inline; the logic has to live in \
.github/scripts/pack-checksums.sh so it can be run and tested"
    printf '     inline hashes: %s\n' \
      "$(printf '%s\n' "$code" | grep -n 'sha256sum\|SHA256SUMS' | head -3 | tr '\n' ' ')"
  else
    ok "build.yml's pack step carries no checksum logic"
  fi
  if printf '%s\n' "$code" | grep -q 'pack-checksums.sh'; then
    ok "build.yml calls .github/scripts/pack-checksums.sh"
  else
    no "build.yml's pack step does not call .github/scripts/pack-checksums.sh"
  fi
}

extract_pack_step() {
  awk '
    BEGIN { state = 0 }
    state == 0 && /^[[:space:]]*- name: Pack \+ checksums[[:space:]]*$/ { state = 1; next }
    state == 1 && /^[[:space:]]*run:[[:space:]]*\|[[:space:]]*$/ { state = 2; next }
    state == 1 && /^[[:space:]]*- / { state = 0 }
    state == 2 {
      if ($0 ~ /^ {10,}/) { print substr($0, 11); next }
      if ($0 ~ /^[[:space:]]*$/) { next }
      exit
    }
  ' "$1"
}

# ── the pre-fix logic, verbatim, so the suite can be shown to notice ─────────
LEGACY_PACK() {
  cat <<'SH'
set -euo pipefail
mkdir -p out
find dist -type f \( -name '*.exe' -o -name '*.zip' -o -name '*.apk' \) | LC_ALL=C sort > /tmp/pack-list
while IFS= read -r f; do
  b="$(basename "$f")"
  if [[ -e "out/$b" ]]; then
    echo "::error::two artifacts flatten to out/$b - existing source vs '$f'"
    exit 1
  fi
  cp -v "$f" "out/$b"
done < /tmp/pack-list
cd out
for f in ./*; do
  [ -f "$f" ] || continue
  sha256sum "$f" | tee "$f.sha256"
done
sha256sum ./* > SHA256SUMS.txt
test -s SHA256SUMS.txt
expected=$(find . -maxdepth 1 -type f ! -name 'SHA256SUMS.txt' ! -name '*.sha256' | wc -l)
actual=$(grep -c . SHA256SUMS.txt)
if [[ "$expected" != "$actual" ]]; then
  echo "::error::SHA256SUMS.txt lists $actual digest(es) for $expected artifact(s)"
  exit 1
fi
sha256sum -c --quiet SHA256SUMS.txt
count=$(find . -maxdepth 1 -name '*.sha256' | wc -l)
if [[ "$count" != "$expected" ]]; then
  echo "::error::$count per-file .sha256 sidecars for $expected artifacts"
  exit 1
fi
{
  echo "tag=latest"
  echo "title=Latest build"
  echo "prerelease=true"
} >> "$GITHUB_OUTPUT"
SH
}

usage() {
  sed -n '2,20p' "$0"
}

MODE=suite
TARGET=
case "${1:-}" in
--against-workflow)
  MODE=workflow
  TARGET=${2:-}
  [ -n "$TARGET" ] || {
    echo "usage: $0 --against-workflow <workflow.yml>" >&2
    exit 2
  }
  ;;
--selftest-fail) MODE=selftest ;;
--help | -h)
  usage
  exit 0
  ;;
'') ;;
*)
  echo "unknown argument '$1'" >&2
  usage
  exit 2
  ;;
esac

WORK=$(mktemp -d "${TMPDIR:-/tmp}/aether-pack-test.XXXXXX")
trap 'rm -rf "$WORK"' EXIT
make_dist "$WORK"

case $MODE in
suite)
  echo "# test-pack-checksums (behavioural suite on pack-checksums.sh)"
  suite_behaviour "$SCRIPT" "$WORK"
  suite_refusals "$WORK"
  suite_flatten_collision "$WORK"
  echo "# static suite on .github/workflows/build.yml"
  suite_workflow "$WORKFLOW"
  ;;
workflow)
  body=$(extract_pack_step "$TARGET")
  if [ -z "$body" ]; then
    echo "no 'Pack + checksums' step body found in $TARGET" >&2
    exit 2
  fi
  printf '%s\n' "$body" >"$WORK/inline.sh"
  echo "# test-pack-checksums (inline step body extracted from $TARGET)"
  suite_behaviour "$WORK/inline.sh" "$WORK"
  suite_workflow "$TARGET"
  ;;
selftest)
  echo "# test-pack-checksums --selftest-fail (the suite must catch the old defect)"
  LEGACY_PACK >"$WORK/legacy.sh"
  mkdir -p "$WORK/legacy"
  cp -r "$WORK/dist" "$WORK/legacy/dist"
  out=$(cd "$WORK/legacy" && GITHUB_OUTPUT="$WORK/legacy/gh-output" bash "$WORK/legacy.sh" 2>&1)
  rc=$?
  echo "  legacy pack exit=$rc"
  echo "  legacy output: $(printf '%s\n' "$out" | grep '::error::' | head -1)"
  if [ "$rc" = "0" ]; then
    no "the pre-fix logic ran clean - nothing here proves the fix was needed"
  else
    ok "the pre-fix logic fails its own pack step"
  fi
  legacy_lines=0
  [ -s "$WORK/legacy/out/SHA256SUMS.txt" ] &&
    legacy_lines=$(grep -c . "$WORK/legacy/out/SHA256SUMS.txt")
  payloads=$(find "$WORK/legacy/out" -maxdepth 1 -type f ! -name 'SHA256SUMS.txt' \
    ! -name '*.sha256' 2>/dev/null | wc -l)
  if [ "$legacy_lines" = "$payloads" ] && [ "$payloads" -gt 0 ]; then
    no "the pre-fix manifest now has one line per payload ($legacy_lines/$payloads); \
the injected defect is no longer reproducible"
  else
    ok "the pre-fix manifest holds $legacy_lines line(s) for $payloads payload(s) - \
it hashes the sidecars it generated"
  fi
  ;;
esac

echo
if [ "$FAILED" = 0 ]; then
  echo "# test-pack-checksums: $PASS check(s) passed"
  exit 0
fi
echo "# test-pack-checksums: $FAILED of $((PASS + FAILED)) check(s) failed"
exit 1
