device_id = "0df2f6f2-8474-42f6-9b32-efd8224e7eaa"
access_token = "a4a10daf-e2ef-4ece-984f-5cc487b5528c"
cert_pem = """
-----BEGIN CERTIFICATE-----
MIH0MIGboAMCAQICCQCj2kFKlVV2azAKBggqhkjOPQQDAjAAMB4XDTI2MDcyMDIy
MTAzMloXDTI2MDcyNzIyMTAzMlowADBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
BJwP3koFKug/zxNuYldkfq9ORJOXfkWpXeNuRx/TAa4sRjTwN0AkSbjKsIRpYocn
y0JbDCDl4oIwMDDMulMWa0MwCgYIKoZIzj0EAwIDSAAwRQIhAIgmjY4/luu3p/bO
eDtDPwWmn3xs85iLNaJZOy7x6ZOgAiALK8WOn3iP7LAsTRRlmGqJKv0SGFz5HvSy
38T5ATItVQ==
-----END CERTIFICATE-----
"""
key_pem = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgT2HuGQS1qG0THIHQ
L4lGTN4B67mqpmJfKmqjRRsrJQmhRANCAAScD95KBSroP88TbmJXZH6vTkSTl35F
qV3jbkcf0wGuLEY08DdAJEm4yrCEaWKHJ8tCWwwg5eKCMDAwzLpTFmtD
-----END PRIVATE KEY-----
"""
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:82d5:459d:b0b:cadd:2118"
wg_private_key = "+B3lRN2YDICdWT0HB2MbO+Cq+wjQAe3o9SahLoVThF0="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "VzgT"
