device_id = "56ea4e71-5a3f-4433-8b1d-0b9e5a04ce21"
access_token = "e801ae1a-8ed3-4b93-b2ff-4049ee931105"
cert_pem = ""
key_pem = ""
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8569:ad6d:4bee:ec13:d22c"
wg_private_key = "QI3LT1JBESGC0QDgxcrTDrv5UZNCmkfApVLO7QRqDn8="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "c6Pv"
