device_id = "39bf3b59-2ec1-41b1-b8c1-a37ccbe935be"
access_token = "47aa3b82-9b5c-4314-baae-551c14250db6"
cert_pem = """
-----BEGIN CERTIFICATE-----
MIH0MIGboAMCAQICCQCNrWTdIklUAzAKBggqhkjOPQQDAjAAMB4XDTI2MDcyMDIy
NDMzN1oXDTI2MDcyNzIyNDMzN1owADBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
BFG9DXNGzuozt5oS2fhe7QZEu4/ITQPN30H9xrweGP7cUZ/uyzBjpF2zlZxroDc8
eADSzg0t3RkvJOKMgkUF7PYwCgYIKoZIzj0EAwIDSAAwRQIgYTaqncYhT+58U65g
W1yvH9RF2pKPZhK7SuMxCICxMgICIQCt7aA6bIw4edV7Nq6uTbedELUX6Y3iLP/1
Y22zTQ32rg==
-----END CERTIFICATE-----
"""
key_pem = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgt+7kYyW1to6MhZBP
nXY8qC5p5c4RVi+7svbcacfxExyhRANCAARRvQ1zRs7qM7eaEtn4Xu0GRLuPyE0D
zd9B/ca8Hhj+3FGf7sswY6Rds5Wca6A3PHgA0s4NLd0ZLyTijIJFBez2
-----END PRIVATE KEY-----
"""
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:864a:dd36:acb4:5603:f538"
wg_private_key = "cFgooLVJW58wwO6T/+y8Wa4jIvkRB0HUr+mn6unIxWM="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "zikm"
